# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Ubuntu - Bash - Hello World

# name of GitHub event that triggers workflow
# on: [push]

# this will effectively DISABLE this workflow
on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:

    # always pin versions
    # view installed software: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

        env | sort
