# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

# name of GitHub event that triggers workflow
on: [push]

jobs:
  build:

    # always pin versions
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

        env | sort
